modid = "hexstonebodies"
book = "hexcasting:thehexbook"

resource_dirs = [
    # top takes priority
    "resources",
    "{$_common.src}/main/resources",

    { path="{$_common.src}/generated/resources", required=false },
    { path="{$_fabric.src}/main/resources", required=false },
    { path="{$_fabric.src}/generated/resources", required=false },
    { path="{$_forge.src}/main/resources", required=false },
    { path="{$_forge.src}/generated/resources", required=false },

    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_hexstonebodies/_export/generated"

[template]
icon = "{$_common.src}/main/resources/assets/hexstonebodies/icon.png"
include = [
    "hexstonebodies",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Hex Corpora Lapidea"
author = "luucyf3r"
show_landing_text = false

[extra.hexcasting]
# regexes for parsing pattern registry files - if some or all of your patterns aren't being detected by hexdoc, this may need to be updated
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"='make\(\s*"(?P<name>[a-zA-Z0-9_/]+)"\s*,\s*HexDir\.(?P<startdir>\w+)\s*,\s*"(?P<signature>[aqweds]+)"\s*,\s*(?P<action>\w+)' }

[[extra.hexcasting.pattern_stubs]]
path = "{$_common.src}/main/kotlin/io/github/luucyf3r/hexstonebodies/registry/HexstonebodiesActions.kt"
regex = "{^_pattern_regex}"

# source paths

[_common]
src = "../src/common"

[_fabric]
src = "../src/fabric/1.21.1"

[_forge]
src = "../src/neoforge/1.21.1"
