# This file is auto-generated by hatch-gradle-version. Do not edit.

GRADLE_VERSION = "1.0.0.1.20.1"
FULL_VERSION = "1.0.0.1.20.1.1.0"

CURSEFORGE_ID = ""
JETBRAINS_ANNOTATIONS_VERSION = "23.0.0"
KOTLIN_STDLIB_DEFAULT_DEPENDENCY = "false"
MAVEN_GROUP = "io.github.luucyf3r.hexstonebodies"
MINECRAFT_VERSION = "1.20.1"
MOD_ID = "hexstonebodies"
MOD_VERSION = "1.0.0"
MODRINTH_ID = ""
ORG_GRADLE_JVMARGS = "-Xmx6096M"
